webtalk_init -webtalk_dir /home/mdescham/Bureau/BE_Controleur_Ethernet/Ethernet10/Ethernet10.sim/sim_1/behav/xsim/xsim.dir/TestRecepteur_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  8 14:35:21 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "97de74f1-4bdb-4e28-98d6-917dc9980b66" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "500a1bc69f124614bd4c15bd84126bf0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "26" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1070.172 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 563175099 -regid "" -xml /home/mdescham/Bureau/BE_Controleur_Ethernet/Ethernet10/Ethernet10.sim/sim_1/behav/xsim/xsim.dir/TestRecepteur_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mdescham/Bureau/BE_Controleur_Ethernet/Ethernet10/Ethernet10.sim/sim_1/behav/xsim/xsim.dir/TestRecepteur_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mdescham/Bureau/BE_Controleur_Ethernet/Ethernet10/Ethernet10.sim/sim_1/behav/xsim/xsim.dir/TestRecepteur_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
